//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_Complaints
    {
        public int ComplaintID { get; set; }
        public string ComplaintNumber { get; set; }
        public Nullable<byte> ComplaintChannelID { get; set; }
        public string PersonMakingReport { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public Nullable<System.TimeSpan> TimeOfIncident { get; set; }
        public Nullable<short> ReceivedByID { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<byte> AcknowledgementID { get; set; }
        public string ClientComplaint { get; set; }
        public Nullable<bool> FeedbackProvided { get; set; }
        public Nullable<System.DateTime> DateOfFeedback { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<byte> ShiftID { get; set; }
    
        public virtual tbl_Ref_Areas tbl_Ref_Areas { get; set; }
        public virtual tbl_Ref_ComplaintChannel tbl_Ref_ComplaintChannel { get; set; }
        public virtual tbl_Ref_ComplaintChannel tbl_Ref_ComplaintChannel1 { get; set; }
        public virtual tbl_Ref_Locations tbl_Ref_Locations { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees { get; set; }
    }
}
