//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sup_DailyMasterRoster
    {
        public int MasterRosterID { get; set; }
        public Nullable<int> PostAssignmentID { get; set; }
        public string OfficerAssigned { get; set; }
        public string ReasonForAbsence { get; set; }
        public string RelievingOfficer { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Sup_DailyPostAssignment tbl_Sup_DailyPostAssignment { get; set; }
    }
}
