//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ref_Regions
    {
        public tbl_Ref_Regions()
        {
            this.tbl_Ref_Locations = new HashSet<tbl_Ref_Locations>();
        }
    
        public byte RegionID { get; set; }
        public string RegionNumber { get; set; }
        public string RegionName { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<tbl_Ref_Locations> tbl_Ref_Locations { get; set; }
    }
}
