//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_IncidentPersonsAffected
    {
        public int PersonAffectedID { get; set; }
        public Nullable<byte> AffectedTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string OtherTypeDescription { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Ref_IncidentPersonAffectedType tbl_Ref_IncidentPersonAffectedType { get; set; }
        public virtual tbl_Op_Incidents tbl_Op_Incidents { get; set; }
    }
}
