//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sup_ShiftReportChecks_Officers
    {
        public long ShiftReportChecksOfficerID { get; set; }
        public Nullable<long> ChecksID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Sup_Employees tbl_Sup_Employees { get; set; }
        public virtual tbl_Sup_ShiftReportChecks tbl_Sup_ShiftReportChecks { get; set; }
    }
}
