//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_Incidents
    {
        public tbl_Op_Incidents()
        {
            this.tbl_Op_IncidentPersonsAffected = new HashSet<tbl_Op_IncidentPersonsAffected>();
        }
    
        public int IncidentID { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<System.DateTime> DateOccured { get; set; }
        public Nullable<System.TimeSpan> TimeOccured { get; set; }
        public Nullable<byte> IncidentTypeID { get; set; }
        public string OtherTypeDescription { get; set; }
        public string Description { get; set; }
        public string IncidentNumber { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public string ActionTaken { get; set; }
    
        public virtual ICollection<tbl_Op_IncidentPersonsAffected> tbl_Op_IncidentPersonsAffected { get; set; }
        public virtual tbl_Ref_Areas tbl_Ref_Areas { get; set; }
        public virtual tbl_Ref_IncidentTypes tbl_Ref_IncidentTypes { get; set; }
        public virtual tbl_Ref_Locations tbl_Ref_Locations { get; set; }
    }
}
