//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_WeeklySecurityReport
    {
        public tbl_Mgr_WeeklySecurityReport()
        {
            this.tbl_Mgr_WeeklySecurityReportComparison = new HashSet<tbl_Mgr_WeeklySecurityReportComparison>();
        }
    
        public int SecurityReportID { get; set; }
        public string ReportNumber { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public Nullable<System.DateTime> WeekStart { get; set; }
        public Nullable<System.DateTime> WeekEnd { get; set; }
        public Nullable<byte> WeekNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Ref_Areas tbl_Ref_Areas { get; set; }
        public virtual ICollection<tbl_Mgr_WeeklySecurityReportComparison> tbl_Mgr_WeeklySecurityReportComparison { get; set; }
    }
}
