//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_WeeklySecurityReportComparison
    {
        public int ComparisonID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<int> SecurityReportID { get; set; }
        public string CashInGT { get; set; }
        public string CashOutGT { get; set; }
        public string Other { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public string Present { get; set; }
        public string Absent { get; set; }
        public string IncidentComplaints { get; set; }
        public string Switches { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Mgr_WeeklySecurityReport tbl_Mgr_WeeklySecurityReport { get; set; }
        public virtual tbl_Ref_Shifts tbl_Ref_Shifts { get; set; }
    }
}
