//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_DailyLogsCallLog
    {
        public long CallLogID { get; set; }
        public Nullable<int> DailyLogID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Reports { get; set; }
        public Nullable<bool> SupCheckLocation { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Op_DailyLogs tbl_Op_DailyLogs { get; set; }
    }
}
