//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_DailyLogsPersonWorking
    {
        public long PersonWorkingID { get; set; }
        public Nullable<int> DailyLogID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public Nullable<System.DateTime> TimeClocked { get; set; }
        public Nullable<bool> IsSwitch { get; set; }
        public Nullable<bool> IsDouble { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Op_DailyLogs tbl_Op_DailyLogs { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees { get; set; }
    }
}
