//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin_User_Role
    {
        public int UserRoleID { get; set; }
        public Nullable<byte> UserID { get; set; }
        public Nullable<short> RoleSubLevelID { get; set; }
        public Nullable<byte> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Admin_RolesSubLevel tbl_Admin_RolesSubLevel { get; set; }
        public virtual tbl_Admin_Users tbl_Admin_Users { get; set; }
    }
}
