//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_WorkSchedule
    {
        public tbl_Mgr_WorkSchedule()
        {
            this.tbl_Mgr_WorkSchedule_Employees = new HashSet<tbl_Mgr_WorkSchedule_Employees>();
        }
    
        public int WorkScheduleID { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual ICollection<tbl_Mgr_WorkSchedule_Employees> tbl_Mgr_WorkSchedule_Employees { get; set; }
        public virtual tbl_Ref_Shifts tbl_Ref_Shifts { get; set; }
    }
}
