//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sup_DailyPostAssignment
    {
        public tbl_Sup_DailyPostAssignment()
        {
            this.tbl_Sup_DailyMasterRoster = new HashSet<tbl_Sup_DailyMasterRoster>();
        }
    
        public int PostAssignmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<short> LateArrivals { get; set; }
        public Nullable<short> CallsForAssistance { get; set; }
        public Nullable<short> OfficersPresent { get; set; }
        public Nullable<short> OfficersAbsent { get; set; }
        public Nullable<short> OfficersAssigned { get; set; }
        public Nullable<short> OfficersCalledOut { get; set; }
        public Nullable<short> OfficersCallInForDayOff { get; set; }
        public Nullable<short> OfficersOnDayOff { get; set; }
        public Nullable<short> NotDressedProperly { get; set; }
        public Nullable<short> Sleeping { get; set; }
        public string ShiftSummary { get; set; }
        public string ShiftBriefingNotes { get; set; }
        public string PassedOnFrom { get; set; }
        public string PassedOnTo { get; set; }
        public string SummaryOfIncidents { get; set; }
        public string ReportNumber { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Ref_Shifts tbl_Ref_Shifts { get; set; }
        public virtual ICollection<tbl_Sup_DailyMasterRoster> tbl_Sup_DailyMasterRoster { get; set; }
    }
}
