//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_CallIn_Absent
    {
        public int CallInOffID { get; set; }
        public Nullable<bool> IsCallIn { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<short> CallTakenByID { get; set; }
        public Nullable<short> ForwardedToID { get; set; }
        public string WorkSchedule { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> AbsentTypeID { get; set; }
        public string OtherTypeDescription { get; set; }
        public Nullable<byte> SickLeaveForID { get; set; }
        public string OtherSickLeaveForTypeDescription { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string ReportNumber { get; set; }
        public Nullable<byte> ShiftID { get; set; }
    
        public virtual tbl_Ref_AbsentType tbl_Ref_AbsentType { get; set; }
        public virtual tbl_Ref_SickLeaveFor tbl_Ref_SickLeaveFor { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees1 { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees2 { get; set; }
    }
}
