//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ref_ComplaintChannel
    {
        public tbl_Ref_ComplaintChannel()
        {
            this.tbl_Op_Complaints = new HashSet<tbl_Op_Complaints>();
            this.tbl_Op_Complaints1 = new HashSet<tbl_Op_Complaints>();
        }
    
        public byte ComplaintChannelID { get; set; }
        public string Channel { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsComplaintsMade { get; set; }
        public Nullable<bool> IsAcknowledgement { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual ICollection<tbl_Op_Complaints> tbl_Op_Complaints { get; set; }
        public virtual ICollection<tbl_Op_Complaints> tbl_Op_Complaints1 { get; set; }
    }
}
