//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_WorkSchedule_Employees
    {
        public tbl_Mgr_WorkSchedule_Employees()
        {
            this.tbl_Mgr_WorkSchedule_Days = new HashSet<tbl_Mgr_WorkSchedule_Days>();
        }
    
        public long WorkScheduleEmployeeID { get; set; }
        public Nullable<int> WorkScheduleID { get; set; }
        public Nullable<short> EmployeeID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<short> StandyByEmployeeID { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> Exclude { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<bool> WasUnscheduled { get; set; }
        public string Comments { get; set; }
    
        public virtual tbl_Mgr_WorkSchedule tbl_Mgr_WorkSchedule { get; set; }
        public virtual ICollection<tbl_Mgr_WorkSchedule_Days> tbl_Mgr_WorkSchedule_Days { get; set; }
        public virtual tbl_Ref_Locations tbl_Ref_Locations { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees { get; set; }
        public virtual tbl_Sup_Employees tbl_Sup_Employees1 { get; set; }
    }
}
