//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ref_Areas
    {
        public tbl_Ref_Areas()
        {
            this.tbl_Mgr_SpecialOperations = new HashSet<tbl_Mgr_SpecialOperations>();
            this.tbl_Op_Complaints = new HashSet<tbl_Op_Complaints>();
            this.tbl_Op_DailyLogs = new HashSet<tbl_Op_DailyLogs>();
            this.tbl_Ref_Locations = new HashSet<tbl_Ref_Locations>();
            this.tbl_Sup_Employees = new HashSet<tbl_Sup_Employees>();
            this.tbl_Sup_ShiftReport = new HashSet<tbl_Sup_ShiftReport>();
            this.tbl_Mgr_WeeklySecurityReport = new HashSet<tbl_Mgr_WeeklySecurityReport>();
            this.tbl_Op_Incidents = new HashSet<tbl_Op_Incidents>();
        }
    
        public byte AreaID { get; set; }
        public string Area { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> Seq { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual ICollection<tbl_Mgr_SpecialOperations> tbl_Mgr_SpecialOperations { get; set; }
        public virtual ICollection<tbl_Op_Complaints> tbl_Op_Complaints { get; set; }
        public virtual ICollection<tbl_Op_DailyLogs> tbl_Op_DailyLogs { get; set; }
        public virtual ICollection<tbl_Ref_Locations> tbl_Ref_Locations { get; set; }
        public virtual ICollection<tbl_Sup_Employees> tbl_Sup_Employees { get; set; }
        public virtual ICollection<tbl_Sup_ShiftReport> tbl_Sup_ShiftReport { get; set; }
        public virtual ICollection<tbl_Mgr_WeeklySecurityReport> tbl_Mgr_WeeklySecurityReport { get; set; }
        public virtual ICollection<tbl_Op_Incidents> tbl_Op_Incidents { get; set; }
    }
}
