//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditLog
    {
        public long AuditLogID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string TableName { get; set; }
        public string AuditProcess { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<byte> UserID { get; set; }
    }
}
