//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_SpecialOperations
    {
        public int SpecialOperationsID { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> EscortService { get; set; }
        public Nullable<bool> CashInGT { get; set; }
        public Nullable<bool> CashOutGT { get; set; }
        public Nullable<bool> ExtraOfficers { get; set; }
        public Nullable<byte> AmountOfficers { get; set; }
        public string Comments { get; set; }
        public string ReportNumber { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<byte> ShiftID { get; set; }
    
        public virtual tbl_Ref_Areas tbl_Ref_Areas { get; set; }
        public virtual tbl_Ref_Locations tbl_Ref_Locations { get; set; }
    }
}
