//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mgr_WorkSchedule_Days
    {
        public long WorkScheduleDateID { get; set; }
        public Nullable<long> WorkScheduleEmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDayOff { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Mgr_WorkSchedule_Employees tbl_Mgr_WorkSchedule_Employees { get; set; }
    }
}
