//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSA.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Op_DailyLogs
    {
        public tbl_Op_DailyLogs()
        {
            this.tbl_Op_DailyLogsCallLog = new HashSet<tbl_Op_DailyLogsCallLog>();
            this.tbl_Op_DailyLogsPersonWorking = new HashSet<tbl_Op_DailyLogsPersonWorking>();
        }
    
        public int DailyLogID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> AreaID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public string LogNumber { get; set; }
        public Nullable<int> WorkScheduleID { get; set; }
        public Nullable<byte> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual tbl_Ref_Areas tbl_Ref_Areas { get; set; }
        public virtual tbl_Ref_Locations tbl_Ref_Locations { get; set; }
        public virtual tbl_Ref_Shifts tbl_Ref_Shifts { get; set; }
        public virtual ICollection<tbl_Op_DailyLogsCallLog> tbl_Op_DailyLogsCallLog { get; set; }
        public virtual ICollection<tbl_Op_DailyLogsPersonWorking> tbl_Op_DailyLogsPersonWorking { get; set; }
    }
}
